### ISSUE TITLE
bugg

### ISSUE THREAD

**Issue by grosfaignan** [splitbrain/php-cli#18]
hello 
your examples files are all bugged, let me know if this librarie is always maintained.
for most it's like : 

> Fatal error: Namespace declaration statement has to be the very first statement or after any declare call in the script in C:\wamp64\www\netshell\shell2\vendor\splitbrain\php-cli\examples\complex.php on line 4

> Warning: require(C:\wamp64\www\netshell\shell2\vendor\splitbrain\php-cli\examples/../vendor/autoload.php): failed to open stream: No such file or directory in C:\wamp64\www\netshell\shell2\vendor\splitbrain\php-cli\examples\logging.php on line 3

> Fatal error: require(): Failed opening required 'C:\wamp64\www\netshell\shell2\vendor\splitbrain\php-cli\examples/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\wamp64\www\netshell\shell2\vendor\splitbrain\php-cli\examples\logging.php on line 3

charly

**Comment by splitbrain** [comment]
sorry, this has not enough details to answer. all example files work for me.
