### ISSUE TITLE
Default options are not available on commands

### ISSUE THREAD

**Issue by kodie** [splitbrain/php-cli#25]
For example, if I register a command:

```php
$options->registerCommand('install', 'Installs packages');
```

and then pass a default option to that command:
```
mycli install --no-colors
```

I get `☠ No such option 'no-colors'`

**Comment by splitbrain** [comment]
order does matter there. try `mycli --no-colors install`

**Comment by kodie** [comment]
@splitbrain ah, that does work! I guess maybe a feature request coming from this then would be to make the order not matter. I could potentially take a stab at it and submit a PR. 🙂
