### ISSUE TITLE
Late log level setup

### ISSUE THREAD

**Issue by smazur** [splitbrain/php-cli#32]
Hi! 

After updating to most recent version of this library i got a fatal error:
> Error: Call to undefined method setLogLevel()

I'm using configuration files and would like to setup log level later after reading app configuration. But now there is no simple way to do that.

It would be nice if you return the `setLogLevel()` method back. Thanks!

**Comment by splitbrain** [comment]
Hmm... I'm a bit confused. Are you sure that method has ever existed? Can you point to a commit where it was removed?

**Comment by smazur** [comment]
@splitbrain 

Oh! Sorry!

I start using the library from [version 1.1.5](https://github.com/splitbrain/php-cli/releases/tag/1.1.5). And there is no that method. It looks like that was my customization... A lot of time has passed since then and i just forgot about that modification.

I definitely have to PR for this functionality :)

**Comment by splitbrain** [comment]
A PR that adds reading configs from a configuration file would be interesting indeed.

**Comment by smazur** [comment]
Hi @splitbrain! 

Do you plan to release the dynamic log level functionality? I would like to update my decencies and  eliminate my custom modifications to keep things clear. 

Thanks a lot!

**Comment by splitbrain** [comment]
thanks for reminding me. I had totally forgotten about this again
