### ISSUE TITLE
'tput' is not recognized as an internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by kAlvaro** [splitbrain/php-cli#5]
On Windows (either CMD or PowerShell) you get extraneous output:

> 'tput' is not recognized as an internal or external command, operable program or batch file

![PowerShell](https://i.imgur.com/MJY2KSM.png)

It comes from `\splitbrain\phpcli\TableFormatter::__construct()`:

    $width = @exec('tput cols');

When the `tput` command is not available the shell prints an error message on stderr and it's apparently transmitted to the shell where you run the PHP script. (Apparently bash is also subject to this but it isn't an issue because ncurses is normally installed.)

**Comment by dregad** [comment]
FWIW, this is how the **[getopt-php](https://github.com/getopt-php/getopt-php)** library (which does pretty much the same thing as this one) implemented terminal width detection (also using _tput_)

https://github.com/getopt-php/getopt-php/blob/3.1.0/src/Help.php#L298

**Comment by kAlvaro** [comment]
It works fine now, thank you very much.
